import Link from "next/link";
import ReactMarkdown from "react-markdown";
import { Button } from "~/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { api } from "~/trpc/server";

const ReviewAnswers = async ({
  params,
}: {
  params: { tutId: string; quizId: string };
}) => {
  const review = await api.review.generateReview.query({
    takenQuizId: params.quizId,
    tutId: params.tutId,
  });

  return (
    <div className="grid p-4 max-w-3xl mx-auto gap-4 justify-center content-around ">
      {/* Title Review Weakneses */}
      {/* Explanation with mnore bnutton that user can click and prompt what they want to learn more about and the user will get the result generated by ai*/}

      <Card>
        <CardHeader>
          <CardTitle className="text-2xl">Review By Lingo Zan</CardTitle>
        </CardHeader>
        <CardContent className="flex-col flex gap-6">
          <ReactMarkdown className="text-xm sm:text-base prose">
            {review.body}
          </ReactMarkdown>
          {/* <MoreInfoDrawer /> */}
        </CardContent>
      </Card>

      <Link href="/" className="w-full">
        <Button className="w-full">Main Page</Button>
      </Link>

      {/* Next button to go to next question review */}
    </div>
  );
};

export default ReviewAnswers;
export const maxDuration = 60;
