"use client";

import ReactMarkdown from "react-markdown";
import { Heading } from "~/components/ui/Typography";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";

const weaknesReview = [
  {
    title: "Doko (Where)",
    content:
      '<b>Doko (Doko)</b> means "where." However, you might have selected the wrong option. Here are some examples to help you understand it better.',
  },
  {
    title: 'Common Mistakes with "Doko" (Where)',
    content:
      '**Mixing up "Doko" with "Koko" (Here):**<br> While both words refer to location, "doko" is used for asking about an unknown location, and "koko" refers to the speaker\'s current location. <br> For example:<br> * Incorrect: "Doko desu ka?"<br> * Correct: "Koko desu ka?" (Is this here?)<br><br> **Forgetting particles:**<br> In Japanese, particles like "wa" (topic marker) are crucial. Don\'t forget to add "wa" after the location word. <br> * Incorrect: "Nihon ikimasu" (I go to Japan) <br> * Correct: "Nihon e ikimasu" (I go to Japan)',
  },
  {
    title: 'Examples of "Doko" (Where) in Japanese',
    content:
      '*  "Koko wa nan desu ka?": Where is this? <br> *  "Toire wa doko desu ka?": Where is the restroom? <br> *  "Tanaka-san wa doko desu ka?": Where is Ms. Tanaka?',
  },
];

const ReviewAnswers = () => {
  return (
    <div className="grid p-4 max-w-3xl mx-auto gap-4 justify-center content-around min-h-screen">
      {/* Title Review Weakneses */}
      <Heading>Review Weaknesses</Heading>
      {/* Explanation with mnore bnutton that user can click and prompt what they want to learn more about and the user will get the result generated by ai*/}
      {weaknesReview.map((content, idx) => {
        return (
          <Card key={idx}>
            <CardHeader>
              <CardTitle>{content.title}</CardTitle>
            </CardHeader>
            <CardContent className="flex-col flex gap-6">
              <ReactMarkdown className="text-xm sm:text-base">
                {content.content}
              </ReactMarkdown>
              {/* <MoreInfoDrawer /> */}
            </CardContent>
          </Card>
        );
      })}
      {/* Next button to go to next question review */}
    </div>
  );
};

export default ReviewAnswers;
